# Generated by Django 2.0.7 on 2018-09-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_dutystation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('dutystation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Dutystation')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Section')),
            ],
        ),
    ]
