# Generated by Django 2.0.7 on 2018-10-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventorytag', models.CharField(max_length=6)),
                ('amr', models.PositiveIntegerField()),
                ('serialnumber', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('comment', models.TextField()),
                ('assetmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Assetmodel')),
                ('assettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Assettype')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Holder')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Purchaseorder')),
            ],
        ),
    ]
