# Generated by Django 2.1.1 on 2018-10-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inventorytag',
            field=models.CharField(max_length=6, verbose_name='Inventory Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serialnumber',
            field=models.CharField(max_length=50, verbose_name='Serial Number'),
        ),
    ]
