# Generated by Django 2.1.1 on 2018-10-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181005_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='email',
            field=models.EmailField(default='email@unicef.org', max_length=254),
        ),
    ]
