# Generated by Django 2.1.1 on 2018-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_holder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amr',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inventorytag',
            field=models.CharField(max_length=6, unique=True, verbose_name='Inventory Tag'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serialnumber',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='holder',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
