# Generated by Django 2.1.1 on 2018-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20181006_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='psbstatus',
            field=models.CharField(choices=[('NONE', 'None'), ('MARKED', 'Marked'), ('EXECUTED', 'Executed')], default='NONE', max_length=10),
        ),
    ]
