# Generated by Django 2.1.1 on 2018-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_asset_psbstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('OBSOLETE', 'Obsolete'), ('LOST', 'Lost')], default='GOOD', max_length=10),
        ),
    ]
