# Generated by Django 2.1.1 on 2018-10-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_holder_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutystation',
            name='name',
            field=models.CharField(db_column='Duty station', max_length=30),
        ),
    ]
