# Generated by Django 2.1.1 on 2018-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20181011_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutystation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Duty station'),
        ),
    ]
