# Generated by Django 2.1.1 on 2018-10-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20181011_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amr',
            field=models.PositiveIntegerField(unique=True, verbose_name='AMR'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Price'),
        ),
    ]
